server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.188.120:3306/discuz?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: 123456

#  thymeleaf:
#    prefix: classpath:/static/
#    suffix: .html

mybatis:
  # type-aliases 扫描路径
  type-aliases-package: com.blog.dusk.entity
  # mapper xml 实现扫描路径
  mapper-locations: classpath:mappers/*.xml
  #mapper-locations: com.blog.dusk.mapper
  property:
    order: BEFORE
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true

#mappers
mapper:
  not-empty: false
  identity: MYSQL
  order: after

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# websocket log config
logging:
  level:
    org.dawn.mapper: DEBUG
    com.example.websocket: DEBUG


